### PR TITLE
fix: bug in appeal creation

### LINKED ISSUE #75: create appeal using auto approval policy does not work
**Description**
If a policy only has auto approval steps, and the appeal gets auto-approved with last approval step as skipped, then with the current logic the appeal is approved but the grant never gets created. 

This scenario occurs only in Create appeal flow. It doesn't occur in policy which has manual steps since the update approval function [checks](https://github.com/goto/guardian/blob/main/core/appeal/service.go#L505) for appeal status where as the create appeal flow [does not](https://github.com/goto/guardian/blob/main/core/appeal/service.go#L279).

**To Reproduce**
- create a policy with only auto-approval steps
    - have the last approval step in policy to be marked as skipped using `when` criteria
- create an appeal using this policy

### PR DESCRIPTION
**Pull request by bsushmith**
- bug: if a policy only has auto approval steps, and the appeal gets auto-approved with last approval step as skipped, then with the current logic the appeal is approved but the grant never gets created. Fix this by adding a check

Closes #75

### CODE REVIEW

File: core/appeal/service.go [hunk 1]
```diff
@@ -276,7 +276,7 @@ func (s *Service) Create(ctx context.Context, appeals []*domain.Appeal, opts ...
 		appeal.Policy = nil
 
 		for _, approval := range appeal.Approvals {
-			if approval.Index == len(appeal.Approvals)-1 && approval.Status == domain.ApprovalStatusApproved {
+			if (approval.Index == len(appeal.Approvals)-1 && approval.Status == domain.ApprovalStatusApproved) || appeal.Status == domain.AppealStatusApproved {
```
Comment (rahmatrhd) [inline core/appeal/service.go:279]: can we add test to this?

Comment (bsushmith) [reply core/appeal/service.go]: updated in the existing test case itself by adding a manual approval step which is skipped

**Review by rahmatrhd — APPROVED** [review]
